#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

ENV ASPNETCORE_URLS=http://+:8000;http://+:80;
ENV ASPNETCORE_ENVIRONMENT=Development

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["CadastroUsuario/CadastroUsuario.csproj", "CadastroUsuario/"]
RUN dotnet restore "CadastroUsuario/CadastroUsuario.csproj"
COPY . .
WORKDIR "/src/CadastroUsuario"
RUN dotnet build "CadastroUsuario.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "CadastroUsuario.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "CadastroUsuario.dll"]